### ISSUE TITLE
Add SQLLite DB

### ISSUE THREAD

**Issue by dstrockis** [AzureADSamples/NativeClient-MultiTarget-DotNet#2]
When it makes sense (shared token cache db)

**Comment by vibronet** [comment]
I don't understand this one. Can you flesh this out further?

**Comment by dstrockis** [comment]
I remember Xamarin supports cross-plat use of a sqllite db on the device... I thought it would be cool to incorporate it somehow.  I'm unclear if we could use such a thing for a shared implementation of a token cache.  We can discuss offline if you prefer.

**Comment by vibronet** [comment]
I don't think I understand the use case. The cache customization is there mostly for mid tiers, given that we cannot guess in advance where tokens will be saved (SQL? MongoDB? Azure blobs? Reddis?...). On devices things are different. Every device platform has its own way of storing info, which is part of the app sandboxing. For all those platforms we provide an OOB cache that just works, no need to customize. The only case that I can think of is for sharing the cache outside of the app sandboxing, but that's a super complicated problem and we have the brokers for that.

**Comment by dstrockis** [comment]
Ok, cool. I was thinking that since the WPF app's cache is extensible, maybe others were too, and it would make sense to have a shared implementation. I wasn't sure about iOS & Android. Sounds like there's no legitimate use case then.
